### ISSUE TITLE
arithmeticcoder can not decoder correctly.

### ISSUE THREAD

**Issue by Jillian2017** [JooyoungLeeETRI/CA_Entropy_Model#1]
Hi, thanks for your open source code. In my situation, different points in feature maps follows a gaussian distribution, and I tried to use your arithmeticcoding, but I found that the decoder process is not correct after certain points. I have checked the detailed information, even the sigma and mean are same with encoder side, it cannot decoder the right symbol, so can you give me some hints about it?

**Comment by JooyoungLeeETRI** [comment]
First of all, thank you for your interest.
From my understanding, you apply our model-based arithmetic coder to your application, right? Or you have a problem in running our test code?

In the case of the former, there may be various reasons. One common mistake is running the feed-forward network using GPU. Although theoretically feed forward networks are deterministic, actually they are not with the current CUDA systems. They have very small difference every time we run the networks, and this very small stochastic mismatch may cause arithmetic coding error on the decoder side. Therefore, I'd like to recommend you use CPU for testing. However, I'm not sure if you have exactly this problem. If you give me more information, that would be helpful.

In addition, if possible, check if all environments are the same as the encoder side. The environments may include not only mu and sigma, the decoded symbols and current target symbol, types of variable (e.g. float32 or float64), or other contexts you have.

If you have a problem running our test code, please let me know error code. Thank you!

**Comment by Jillian2017** [comment]
Thanks very much for your advices and sorry for the late reply.
According to your advice, I found that there exist small deviation for mu and sigma between encoder and decoder while using GPU, about e-4, so I think this can explain why I cannot decoder successfully. 
As you mentioned the reason of the CUDA system, I have tested on CPU, the code can run well, thanks a lot.

**Comment by JooyoungLeeETRI** [comment]
It really sounds good. It seems that the non-determinism comes from the structure of GPU computation for parallel processing, and it looks like a generally discussed issue. We can check this later when NN-based compression becomes practical (in the near future?). Anyway, I'll close this issue. If you have any question, please let me know. Thank you for your interest again.
