### ISSUE TITLE
KeyError: "The name 'prefix/clip_by_value:0' refers to a Tensor which does not exist. The operation, 'prefix/clip_by_ value', does not exist in the graph."

### ISSUE THREAD

**Issue by Y-pandaman** [JooyoungLeeETRI/CA_Entropy_Model#10]
KeyError: "The name 'prefix/clip_by_value:0' refers to a Tensor which does not exist. The operation, 'prefix/clip_by_
value', does not exist in the graph."
  def build_model(self):
        frozen_graph_filename = self.model_dir + "/" + "saved_model.pb"
        graph = self.load_graph(frozen_graph_filename)

        # for verifying
        # for op in graph.get_operations():
        #     print(op.name)

        self.recon_image = graph.get_tensor_by_name('prefix/clip_by_value:0')
        self.y_hat = graph.get_tensor_by_name('prefix/transpose_3:0')
        self.input_x = graph.get_tensor_by_name('prefix/Placeholder_2:0')
        self.c_prime = graph.get_tensor_by_name('prefix/transpose_8:0')
        self.z_hat = graph.get_tensor_by_name('prefix/Round_1:0')
        self.sigma_z = graph.get_tensor_by_name('prefix/H/Abs:0')
        self.pred_mean = graph.get_tensor_by_name('prefix/H/P_31/strided_slice:0')
        self.pred_sigma = graph.get_tensor_by_name('prefix/H/P_31/Exp:0')
        self.concatenated_c_i = graph.get_tensor_by_name('prefix/H/concat_31:0')

**Comment by JooyoungLeeETRI** [comment]
Hello, 
Thank you for your interest. 
Did you succeed to download the models (.pb files)? 

Let me know if you still have a problem even after the models are correctly prepared under the ./models directory.

And for your information, 
we're going to upload the second version of our test codes (that use THE SAME model files)  in a few days. We've improved inefficient padding operations, and also corrected some bugs on integer divisions.

So, I'd like to recommend you download the second version a few days later.  I'll upload it ASAP.

**Comment by Y-pandaman** [comment]
Thank you for the your response.

no,I didn't succeed.I used this code in anaconda3:python encode.py --model_type 0 --input_path ./examples/input
_example.png --compressed_file_path ./examples/output.cmp --quality_level 5,and I manually created ./models/MSEopt/Base_model/5/saved_model.pb,but that error still occurs.I am looking forward to the second version.

**Comment by JooyoungLeeETRI** [comment]
Actually modification on our second version has nothing to do with the model loading process. So.. I think your issue is independent from the version change.

Did you download the full model files from our Google drive and unzip all the models under the "./models' directory?

If so, can you check the file size of "./models/MSEopt/Base_model/5/saved_model.pb"?

**Comment by Y-pandaman** [comment]
> 
> 
> Actually modification on our second version has nothing to do with the model loading process. So.. I think your issue is independent from the version change.
> 
> Did you download the full model files from our Google drive and unzip all the models under the "./models' directory?
> 
> If so, can you check the file size of "./models/MSEopt/Base_model/5/saved_model.pb"?

**Comment by Y-pandaman** [comment]
I didn`t download the full model files,can you give me a download link,?or send it to my email:2575249103@qq.com.thank you!

**Comment by JooyoungLeeETRI** [comment]
You can download the zip file containing the models via the following link:
https://drive.google.com/open?id=1NqIYWOJP4o_JbUl2n2SdxezZNVdpBw5c

If you still have a problem, please let me know again.
