### ISSUE TITLE
Where is the defination of model?

### ISSUE THREAD

**Issue by qiusuor** [JooyoungLeeETRI/CA_Entropy_Model#13]

**Comment by JooyoungLeeETRI** [comment]
I'm sorry. This repository only provides the test version, at the moment.

**Comment by qiusuor** [comment]
不开源的东西传到github干什么？

**Comment by qiusuor** [comment]
不讲武德

**Comment by Jillian2017** [comment]
> 不讲武德

在公司的成果不是想开源就能开源的！能做到这样已经很不错了，还要什么自行车！伸手党这么嚣张吗？！耗子喂汁！

**Comment by qiusuor** [comment]
> > 不讲武德
> 
> 在公司的成果不是想开源就能开源的！能做到这样已经很不错了，还要什么自行车！伸手党这么嚣张吗？！耗子喂汁！
知道了，叶叶！
