### ISSUE TITLE
Questions about RD curves on CLIC validation set

### ISSUE THREAD

**Issue by xyq7** [JooyoungLeeETRI/CA_Entropy_Model#15]
Hi Jooyoung,

Is it possible to release the value of RD points on CLIC validation set? We are working on some related topics and would like to compare with your results. We will really appreciate it! Thanks.

**Comment by JooyoungLeeETRI** [comment]
Hi, 
Thanks for your interest. Here's the result on the CLIC validation set.
Github doesn't allow to attach CSV or XLS form files. If you need them, please email me.
Hope this helps!

Optimized for MSE			
MSSSIM	MS-SSIM (dB form)	PSNR	BPP
0.933120565	11.74707405	29.95608608	0.07808283
0.944621045	12.56655247	30.90512642	0.109127718
0.954900062	13.45824052	31.87011838	0.148732563
0.964512294	14.49922076	33.00016676	0.212732788
0.974109834	15.86865169	34.43053501	0.304070599
0.982915143	17.67388642	36.19456533	0.478043033
0.988505644	19.39515349	37.96750571	0.70136054
0.991483763	20.69752257	39.23028192	0.919859139
0.993861266	22.11921149	40.58481332	1.19890171
			
Optimized for MS-SSIM			
MSSSIM	MS-SSIM (dB form)	PSNR	BPP
0.967061774	14.82299801	30.12016772	0.153751136
0.973821281	15.82051602	30.66920957	0.173446409
0.979516818	16.88602571	31.31745163	0.213108384
0.984702714	18.15385627	31.94931224	0.297217189
0.990310454	20.13696565	33.25234981	0.473592335
0.993665605	21.9829487	34.48988865	0.683376846
0.995370192	23.34437022	35.50853033	0.883689492
0.996858419	25.0285171	36.71545486	1.190796878
0.997814592	26.60467387	37.95585583	1.57736641

**Comment by xyq7** [comment]
Thank you very much!!!!
