### ISSUE TITLE
AssertionError in arithmeticcoding.py 

### ISSUE THREAD

**Issue by mia-7** [JooyoungLeeETRI/CA_Entropy_Model#16]
Dear Jooyoung,
When I use the decode.py to decode the img.bin, it errors. 
![PNG图像](https://user-images.githubusercontent.com/58288009/114176651-0c7e7b00-996e-11eb-9f79-72f3205f681e.png)
Could you help me find the question？

**Comment by JooyoungLeeETRI** [comment]
Dear Mia,
I'm sorry for late response. Did you use GPU for decoding? It causes an en-decoder mismatch problem.
If so, you should use CPU when executing "h_s" and "f" on the decoder side, whereas the following "g_s" part can be executed on GPU.

[g_s]
recon = self.sess.run(self.recon_image, {self.y_hat: y_hat})

Let me know if you have any further question.

**Comment by mia-7** [comment]
Dear Jooyoung,
Yesterday,I changed my dataset and the problem didn’t occur again. Your reply helps me a lot and I will use CPU to decode next time.
Thank you for your help and comprehensive reply.

**Comment by JooyoungLeeETRI** [comment]
Dear Mia,
I'm glad you solved the problem. Hope you have good results! :-)
