### ISSUE TITLE
questions about decoding time

### ISSUE THREAD

**Issue by Jillian2017** [JooyoungLeeETRI/CA_Entropy_Model#2]
Hi, thanks again for your advice in last issue, it does work well. 
But I come across another question, I find that if the image's resolution is very high, such as 2k*1k, it will take quite a lot of time(one hour at least) to decode the bit  stream under cpu mode. How's it going with your side?

**Comment by JooyoungLeeETRI** [comment]
As far as I remember correctly, it took much less time with our environments (around several minutes), although high-bpp models took more. At the moment, we are training other models with the machines, so it's hard to measure them correctly. We'll check the duration after these on-going training jobs. We'd appreciate if you understand :-). Thank you!

**Comment by JooyoungLeeETRI** [comment]
We're sorry for late reply. We conducted simple tests to measure duration time of en/decoding single 2K image. The results are as below. Those are measured based on the start and end time points of console commands:

[Base (quality_level 5)]
  - Encoding Dur.: 70s (1m 10s)
  - Decoding Dur.: 222s (3m 42s)

[Biggest Hybrid Model (quality_level 9)]
  - Encoding Dur.: 191s (3m 11s)
  - Decoding Dur.: 661s (11m 1s)

The results are not promising in terms of complexity, but it was not a hour-long process. For your information, we used i9-7900x CPU(3.30GHz) with 64GB RAM for the tests.

Hope this helps you.

**Comment by Jillian2017** [comment]
Thanks so much for your testing. Your results are more promising than mine, and my testing environment is i7-4790 CPU(3.6GHz), I will do further check. By the way, is the biggest hybird model more complex than base model ? In my side, if the input image is 1024*2048, y'shape is 64*128*192(h*w*c), I think it's very large number, what about yours?

**Comment by JooyoungLeeETRI** [comment]
That's correct. In the case of the base model, w and h is 16 times smaller (four times of downscaling) than the input image, and the number of channels becomes 192 (Parameter M in the paper). We used an 1088 x 1920 image for the test above. In this case the dimension of y will be 68 120 192 for the base model.

With regard to the complexity, the hybrid model is more complex than the model. Please refer to our paper for the detailed network structure :-)

**Comment by Jillian2017** [comment]
OK, I see. Thank you again for your kind and detailed reply. I will read your paper again and reconsider my work.
