### ISSUE TITLE
How to encode more than 1 image file

### ISSUE THREAD

**Issue by B-Aktanin** [JooyoungLeeETRI/CA_Entropy_Model#21]
I use : python encode.py --model_type 0 --input_path ./examples/*.png --quality_level 5 --no_proc 4

#there are 5 images in file examples and error happened : encode.py: error: unrecognized arguments: ./examples/kodim02.png ./examples/kodim03.png ./examples/kodim04.png ./examples/kodim05.png

**Comment by JooyoungLeeETRI** [comment]
I appreciate your interest in our work.
Regarding your question, as I mentioned on the GitHub page, some environments expand the asterisk to every matching file before passing the arguments. Why don't you use quotes for that as below?
python encode.py --model_type 0 --input_path './examples/*.png' --quality_level 5 --no_proc 4

From my understanding, this prevents expanding the wildcard.

**Comment by B-Aktanin** [comment]
Thanks a lot for your reply, I did what you told and it worked very well. ^_^
