### ISSUE TITLE
The arithmetic coding is an lossless method but why when I reconstruct the image the filesize is decreased is it loss because of quantization method 

### ISSUE THREAD

**Issue by B-Aktanin** [JooyoungLeeETRI/CA_Entropy_Model#22]

**Comment by B-Aktanin** [comment]
Thank you in advanced

**Comment by B-Aktanin** [comment]
is the loss happened because of ga, ha, gs and hs too

**Comment by JooyoungLeeETRI** [comment]
Thanks for your interest. Arithmetic coding is a lossless coding tool, but our overall method is lossy coding.
The target to be entropy-coded is transformed and quantized representation, so there must be losses between the original inputs and their reconstructions.

I don't exactly catch your second question, but if you are asking whether the transform functions contribute to the loss together, yes they do.

Hope this helps!

**Comment by B-Aktanin** [comment]
Yes, you answered all of my questions. Thank you very much for your time.
