### ISSUE TITLE
What does the folder's name under "Reconstructed images" indicate ?

### ISSUE THREAD

**Issue by yash0307** [JooyoungLeeETRI/CA_Entropy_Model#5]
I am unable to figure out what the sub-folders: 0.1, 0.2, 0.3, 0.4, 0.5 indicate ? Is the the bpp ? If yes, why does the images with lower bit-rate look better ?

**Comment by yash0307** [comment]
Are they "lambda" ?

**Comment by JooyoungLeeETRI** [comment]
Yes. Those indicate lambda.
I'm sorry for late response. I'm don't know why github does not send me a new issue notification. I'm going to check my configurations. If I don't respond, please send a mail to leejy1003@etri.re.kr
