### ISSUE TITLE
Is it possible for authors to release Urban100 images at different bit-rates ?

### ISSUE THREAD

**Issue by yash0307** [JooyoungLeeETRI/CA_Entropy_Model#6]
Requesting authors to release Urban-100 images as well on different bit-rates. It will be very helpful.

Thanks.

**Comment by JooyoungLeeETRI** [comment]
Current models support en/decoding of other types of images, as well as Kodak images. Do you have any problem on it? Or do you mean training some specialized versions for Urban-100 images?
