### ISSUE TITLE
Referenced images

### ISSUE THREAD

**Issue by Jillian2017** [JooyoungLeeETRI/CA_Entropy_Model#7]
Hi, Lee:
Thanks a lot for sharing evaluation results. I find there are some comparison results in your paper, like Ball´e et al. (2018). I want to know how do you get their results. Is it convenient for you to share them with me?
Looking froward to your reply.
Jillian

**Comment by JooyoungLeeETRI** [comment]
Hi Jillian,
Thank you for your interest.
Regarding the results, we obtained some of them from web, and the others we asked the authors. In the case of conventional codecs, we measured by ourselves using open-source codecs.

We can share the results of the conventional codecs, such as JPEG2000 and BPG, measured by ourselves, but for the other results, I'd like you to ask the authors of the original papers. I believe that they will be happy to share their results with you :-)

**Comment by Jillian2017** [comment]
Hi，Lee:
Thanks a lot. Please share BPG's results with me if you are convenient. I will ask the authors to get their results. 
Best regards.
Jillian

**Comment by JooyoungLeeETRI** [comment]
Okay, let me know your email address.
Thank you.

**Comment by Jillian2017** [comment]
My email is zhoujing@cn.fujitsu.com. Thanks again.
