### ISSUE TITLE
The source code of model

### ISSUE THREAD

**Issue by shellhuang1227** [JooyoungLeeETRI/CA_Entropy_Model#8]
Dear,

The code you have provided is for tesitng. I would like to revise the model and achieve the purpose in my work. So may I ask you for the source code of the model for reference.
Thank you very much.

Best wishes.

**Comment by JooyoungLeeETRI** [comment]
First of all, thank you for your interest.
Unfortunately, we don't have a plan to distribute the training code, at the moment,  for the reason described in https://github.com/JooyoungLeeETRI/CA_Entropy_Model/issues/4.

Please understand our situation and we'll do that as soon as the issue is resolved.
Thank you!!

Regards

**Comment by shellhuang1227** [comment]
Yeah. Really hope you can resolve the issue as soon as possible. 

By the way, when I ran the test code, a error appeared, as followings:
"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1NqIYWOJP4o_JbUl2n2SdxezZNVdpBw5c (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f574fbc29e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))" 

I guess the reason is that the computer can not connect google in China. So can you provide a mirror to let me download the model.zip.

Thank you very much.

**Comment by JooyoungLeeETRI** [comment]
Please try to download via:
https://www.dropbox.com/sh/75dt4lkf4lofvsn/AADyS5ky9bpsMNYpOGtPhI1ya?dl=0

If you have any problem, please let me know again!

**Comment by shellhuang1227** [comment]
It's OK. Thank you very much.
